import { defineField, defineType } from 'sanity'

/**
 * Sanity Coupon document.
 *
 * Coupons are fully manageable from Sanity Studio.
 * Whenever an admin creates, updates, or deletes a Coupon here,
 * Sanity fires a webhook to POST /api/webhooks/sanity which writes
 * the change back to PostgreSQL.
 *
 * Document ID convention: "coupon-{postgresId}" when synced from Postgres,
 * or auto-generated by Sanity on Studio creation.
 *
 * The `pgId` field stores the Postgres Coupon.id to enable back-sync.
 * It is populated automatically by the webhook handler; admins never edit it.
 */
export const couponType = defineType({
  name: 'coupon',
  title: 'Coupon',
  type: 'document',
  groups: [
    { name: 'main', title: 'Coupon Details', default: true },
    { name: 'limits', title: 'Limits & Expiry' },
  ],
  fields: [
    // ── Internal reference (hidden) ──────────────────────────────────────────
    defineField({
      name: 'pgId',
      title: 'PostgreSQL Coupon ID',
      type: 'string',
      description: 'Auto-managed — do not edit.',
      readOnly: true,
      hidden: true,
    }),

    // ── Core fields ──────────────────────────────────────────────────────────
    defineField({
      name: 'code',
      title: 'Coupon Code',
      type: 'string',
      group: 'main',
      description: 'Unique uppercase code customers enter at checkout (e.g. SUMMER20)',
      validation: (Rule) =>
        Rule.required()
          .uppercase()
          .min(3)
          .max(50)
          .regex(/^[A-Z0-9_-]+$/, { name: 'alphanumeric', invert: false }),
    }),

    defineField({
      name: 'description',
      title: 'Description',
      type: 'string',
      group: 'main',
      description: 'Internal note about this coupon (not shown to customers)',
    }),

    defineField({
      name: 'discountType',
      title: 'Discount Type',
      type: 'string',
      group: 'main',
      options: {
        list: [
          { title: 'Percentage (%)', value: 'PERCENTAGE' },
          { title: 'Fixed Amount (SYP)', value: 'FIXED' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'discountValue',
      title: 'Discount Value',
      type: 'number',
      group: 'main',
      description: 'Percentage (0–100) for PERCENTAGE type, or fixed amount in SYP for FIXED type',
      validation: (Rule) => Rule.required().min(0),
    }),

    defineField({
      name: 'isActive',
      title: 'Active',
      type: 'boolean',
      group: 'main',
      description: 'Disable to prevent customers from using this coupon without deleting it',
      initialValue: () => true,
    }),

    // ── Limits & Expiry ──────────────────────────────────────────────────────
    defineField({
      name: 'minOrderAmount',
      title: 'Minimum Order Amount (SYP)',
      type: 'number',
      group: 'limits',
      description: 'Coupon only applies if cart total meets this threshold. Leave empty for no minimum.',
      validation: (Rule) => Rule.min(0),
    }),

    defineField({
      name: 'maxUses',
      title: 'Maximum Total Uses',
      type: 'number',
      group: 'limits',
      description: 'Maximum number of times this coupon can be used across all customers. Leave empty for unlimited.',
      validation: (Rule) => Rule.integer().min(1),
    }),

    defineField({
      name: 'usedCount',
      title: 'Times Used',
      type: 'number',
      group: 'limits',
      description: 'Auto-updated by the system after each successful checkout — do not edit manually.',
      readOnly: true,
      initialValue: () => 0,
      validation: (Rule) => Rule.min(0),
    }),

    defineField({
      name: 'expiresAt',
      title: 'Expiry Date',
      type: 'datetime',
      group: 'limits',
      description: 'Leave empty for a coupon that never expires',
    }),
  ],

  preview: {
    select: {
      code: 'code',
      discountType: 'discountType',
      discountValue: 'discountValue',
      isActive: 'isActive',
      usedCount: 'usedCount',
      maxUses: 'maxUses',
    },
    prepare({ code, discountType, discountValue, isActive, usedCount, maxUses }) {
      const activeLabel = isActive ? '🟢' : '🔴'
      const discountLabel =
        discountType === 'PERCENTAGE'
          ? `${discountValue}% off`
          : `${discountValue?.toLocaleString()} SYP off`
      const usageLabel = maxUses
        ? `${usedCount ?? 0}/${maxUses} uses`
        : `${usedCount ?? 0} uses`
      return {
        title: `${activeLabel} ${code}`,
        subtitle: `${discountLabel} · ${usageLabel}`,
      }
    },
  },

  orderings: [
    {
      title: 'Newest First',
      name: 'createdAtDesc',
      by: [{ field: '_createdAt', direction: 'desc' }],
    },
    {
      title: 'Code A–Z',
      name: 'codeAsc',
      by: [{ field: 'code', direction: 'asc' }],
    },
  ],
})
